import 'package:flutter/material.dart';
import 'package:flutter_tts/flutter_tts.dart';


class EmGame extends StatefulWidget {
  const EmGame({super.key});

  @override
  State<EmGame> createState() => _EmGameState();
}

class _EmGameState extends State<EmGame> {
  FlutterTts flutterTts = FlutterTts();
  final String generatedText = "This is the text generated by the AI.";

  Future<void> _speakText() async {
    await flutterTts.setLanguage("en-US"); // Set the desired language
    await flutterTts.setPitch(1.0); // Set the pitch (default: 1.0)
    await flutterTts.setSpeechRate(0.5); // Set the speech rate (default: 1.0)
    await flutterTts.speak(generatedText);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ElevatedButton(onPressed: () {_speakText();}, child: Text('dvbcn')),

    );
  }
}